### ISSUE TITLE
Crash when using `runtimeChecked` on a refinement type containing a skolem

### ISSUE THREAD

**Issue by smarter** [mbovel/dotty#9]
## Compiler version

Branch `refinements` at https://github.com/mbovel/dotty/commit/ce32c6968b3035ad8110dddd322c2549b169a745

## Minimized code

```Scala
import language.experimental.setNotation

def foo(x: Int, y: {v: Int with v > x}): Unit = ()

@main def TestInt: Unit =
  // ok
  foo(1, 2.runtimeChecked)

  // ok
  val p: Int = 1
  foo(p, 2.runtimeChecked)

  // crash
  foo((1: Int), 2.runtimeChecked)
```

## Output (click arrow to expand)
<details>

```scala
Exception in thread "main"
  unhandled exception while running QualifiedTypesTypeTests on tests/run-custom-args/qualified-types/runtime-check-1.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/lampepfl/dotty/issues/new/choose
  For non-enriched exceptions, compile with -Yno-enrich-error-messages.

     while compiling: tests/run-custom-args/qualified-types/runtime-check-1.scala
        during phase: QualifiedTypesTypeTests
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.12
    compiler version: version 3.4.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-ce32c69
            settings: -Vprint List(erasure) -classpath /home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/home/smarter/opt/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.4.1-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.4.1-RC1-bin-SNAPSHOT.jar -d / -language List(experimental.qualifiedTypes, experimental.setNotation)
java.lang.AssertionError: assertion failed: no overloads available for > on Int with targs: ; args: true; expectedType: Boolean.all alternatives: def >(x: Double): Boolean, def >(x: Float): Boolean, def >(x: Long): Boolean, def >(x: Int): Boolean, def >(x: Char): Boolean, def >(x: Short): Boolean, def >(x: Byte): Boolean
matching alternatives: .
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at dotty.tools.dotc.ast.Trees$Instance.applyOverloaded(Trees.scala:1908)
        at dotty.tools.dotc.qualifiers.QualifierExprs$.binOpToTree$1(QualifierExprs.scala:100)
        at dotty.tools.dotc.qualifiers.QualifierExprs$.boolBinOpToTree$1(QualifierExprs.scala:103)
        at dotty.tools.dotc.qualifiers.QualifierExprs$.toTree(QualifierExprs.scala:122)
        at dotty.tools.dotc.qualifiers.QualifiedTypesTypeTests.$anonfun$3(QualifiedTypesTypeTests.scala:88)
        at dotty.tools.dotc.ast.tpd$.letBindUnless(tpd.scala:1371)
        at dotty.tools.dotc.ast.tpd$.evalOnce(tpd.scala:1379)
        at dotty.tools.dotc.qualifiers.QualifiedTypesTypeTests.transformTypeTest(QualifiedTypesTypeTests.scala:91)
        at dotty.tools.dotc.qualifiers.QualifiedTypesTypeTests.transformTypeApply(QualifiedTypesTypeTests.scala:54)
        at dotty.tools.dotc.transform.MegaPhase.goTypeApply(MegaPhase.scala:692)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:317)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:321)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.loop$2$$anonfun$1(MegaPhase.scala:470)
        at dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:472)
        at dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:472)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:311)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.loop$3(MegaPhase.scala:482)
        at dotty.tools.dotc.transform.MegaPhase.transformTrees(MegaPhase.scala:482)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:292)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.loop$2$$anonfun$1(MegaPhase.scala:470)
        at dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:472)
        at dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:472)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:311)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:261)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:264)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:448)
        at dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:461)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:461)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:372)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:268)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:448)
        at dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:461)
        at dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:461)
        at dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:392)
        at dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:395)
        at dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:450)
        at dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:477)
        at dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:489)
        at dotty.tools.dotc.transform.MegaPhase$MiniPhase.run(MegaPhase.scala:138)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:359)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:365)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:337)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:350)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:360)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:360)
        at dotty.tools.dotc.Run.compileSources(Run.scala:261)
        at dotty.tools.dotc.Run.compile(Run.scala:246)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.dotc.Driver.process(Driver.scala:196)
        at dotty.tools.dotc.Driver.process(Driver.scala:164)
        at dotty.tools.dotc.Driver.process(Driver.scala:176)
        at dotty.tools.dotc.Driver.main(Driver.scala:206)
```
</details>

## Expected behavior

To avoid issues with skolems in arguments, we need to lift complex arguments into their own variables:
```scala
  foo((1: Int), 2.runtimeChecked)
// should be transformed into:
  val x$1 = (1: Int)
  foo(x$1, 2.runtimeChecked)
```
(This is similar to some of the lifting done in https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala)
Lifting is necessary because we need to be able to refer to the previous argument to generate the runtime check, so it must be defined in a variable before the method call.

**Comment by mbovel** [comment]
Fixed: https://github.com/scala/scala3/pull/21586/changes/5424b1cfff26a50ebf67a67275d784e03299abce.
